name: contrib-viz
channels:
- conda-forge
dependencies:
- conda-forge::gitpython=3.1.14
- conda-forge::ipykernel=5.1.0
- conda-forge::ipywidgets=7.4.2
- conda-forge::nb_conda_kernels=2.2.1
- conda-forge::notebook=5.7.5
- conda-forge::pandas=0.24.1
- conda-forge::plotnine=0.5.1
- conda-forge::python=3.6.7
- conda-forge::pyyaml=3.13
- conda-forge::requests=2.21.0
- conda-forge::tornado=4.5.3
- conda-forge::r-base=3.5.1
- conda-forge::r-cowplot=0.9.4
- conda-forge::r-dplyr=0.8.0
- conda-forge::r-gdtools=0.1.7
- conda-forge::r-ggplot2=3.1.0
- conda-forge::r-ggridges=0.5.1
- conda-forge::r-irkernel=0.8.15
- conda-forge::r-lubridate=1.7.4
- conda-forge::r-readr=1.3.1
- conda-forge::r-svglite=1.2.1
- conda-forge::r-tidyr=0.8.2
